version: '3'
services:
  nginx: 
    build: ./nginx
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "80:80"
    depends_on:
      - api
      - client
    restart: always
  client: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /usr/app/node_modules
      - ./client:/usr/app
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /usr/app/node_modules
      - ./server:/usr/app

