# only ebs architecture
version: '3'
services:
  nginx: 
    build: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - api
      - client
    restart: always
  client: 
    build: ./client
  api:
    build: ./server
